### ISSUE TITLE
Cannot find dm input box

### ISSUE THREAD

**Issue by xtream111** [11AnJo/tiktok_dm#2]
Hi,

When trying to send a message, it throws the error "ERROR - Cannot find dm input box"

Is there any config i am doing wrong?

> `from tiktok_web import Session
> 
> session = Session() 
> 
> message = "Hello"
> 
> session.send_msg(username="my_own_account_username", msg=message)`

**Comment by 11AnJo** [comment]
As my testing I know its happening very rarelly when for some reason tiktok is not starting a chat as it should do. 

Its pretty rare, thus I'm always giving it few tries to send message.

If its happening to you always I would have to check it more deeply. So let me know :)

**Comment by xtream111** [comment]
I have tried multiple times without success. 

I can see how the website searches the user and prompts the message page, once it reaches there, it throws the error

**Comment by 11AnJo** [comment]
Could you share page source when this error happens? 

I will check xpath, it is possible that tiktok serves you different version or something is obstructing message box.

**Comment by 11AnJo** [comment]
@xtream111 are you using a business account? 

I just stumbled into same bug as you on a business account, its loading chat as an iframe thus script can't access its data. 

Expect bugfix in short time
